import { pro1, pro2, pro3, pro4, pro5 } from "./assets/images";

export const productsData = {
  products: [
    // Lọc gió động cơ - Air Filter
    {
      id: 1,
      name: "Lọc gió động cơ Air Filter – Chevrolet Colorado, Trailblazer (52046262)",
      image: pro1,
      originalPrice: 329000,
      salePrice: 299000,
      discount: 10,
      status: "Giá cực sốc",
      category: "loc_gio_dong_co",
      brand: "Chevrolet",
      year: 2021,
      origin: "Đức",
      inStock: true,
    },
    {
      id: 2,
      name: "Lọc gió động cơ Air Filter – Ford Ranger, Everest (AB39-9601-AA)",
      image: pro2,
      originalPrice: 350000,
      salePrice: 320000,
      discount: 9,
      status: "Giá cực sốc",
      category: "loc_gio_dong_co",
      brand: "Ford",
      year: 2020,
      origin: "Mỹ",
      inStock: true,
    },
    {
      id: 3,
      name: "Lọc gió động cơ Air Filter – Toyota Hilux, Fortuner (17801-30070)",
      image: pro3,
      originalPrice: 380000,
      salePrice: 340000,
      discount: 11,
      status: "Giá cực sốc",
      category: "loc_gio_dong_co",
      brand: "Toyota",
      year: 2021,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 4,
      name: "Lọc gió động cơ Air Filter – Mazda BT-50 (PE01-13-Z40)",
      image: pro4,
      originalPrice: 310000,
      salePrice: 280000,
      discount: 10,
      status: "Giá cực sốc",
      category: "loc_gio_dong_co",
      brand: "Mazda",
      year: 2019,
      origin: "Nhật Bản",
      inStock: true,
    },

    // Lọc nhiên liệu - Fuel Filter
    {
      id: 5,
      name: "Lọc nhiên liệu Fuel Filter – Chevrolet Colorado, Trailblazer (12642623)",
      image: pro5,
      originalPrice: 450000,
      salePrice: 399000,
      discount: 11,
      status: "Giá cực sốc",
      category: "loc_nhien_lieu",
      brand: "Chevrolet",
      year: 2021,
      origin: "Đức",
      inStock: true,
    },
    {
      id: 6,
      name: "Lọc nhiên liệu Fuel Filter – Ford Ranger, Everest (2S6Q-9176-BA)",
      image: pro1,
      originalPrice: 480000,
      salePrice: 420000,
      discount: 13,
      status: "Giá cực sốc",
      category: "loc_nhien_lieu",
      brand: "Ford",
      year: 2020,
      origin: "Mỹ",
      inStock: true,
    },
    {
      id: 7,
      name: "Lọc nhiên liệu Fuel Filter – Toyota Hilux, Fortuner (23390-0L041)",
      image: pro2,
      originalPrice: 520000,
      salePrice: 460000,
      discount: 12,
      status: "Giá cực sốc",
      category: "loc_nhien_lieu",
      brand: "Toyota",
      year: 2021,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 8,
      name: "Lọc nhiên liệu Fuel Filter – Mazda BT-50 (WL01-13-480)",
      image: pro3,
      originalPrice: 430000,
      salePrice: 380000,
      discount: 12,
      status: "Giá cực sốc",
      category: "loc_nhien_lieu",
      brand: "Mazda",
      year: 2019,
      origin: "Nhật Bản",
      inStock: true,
    },

    // Bộ lọc dầu - Oil Filter
    {
      id: 9,
      name: "Bộ lọc dầu Oil Filter – Chevrolet Colorado, Trailblazer (12636838)",
      image: pro4,
      originalPrice: 280000,
      salePrice: 250000,
      discount: 11,
      status: "Giá cực sốc",
      category: "bo_loc_dau",
      brand: "Chevrolet",
      year: 2021,
      origin: "Đức",
      inStock: true,
    },
    {
      id: 10,
      name: "Bộ lọc dầu Oil Filter – Ford Ranger, Everest (1S7G-6714-DA)",
      image: pro5,
      originalPrice: 300000,
      salePrice: 270000,
      discount: 10,
      status: "Giá cực sốc",
      category: "bo_loc_dau",
      brand: "Ford",
      year: 2020,
      origin: "Mỹ",
      inStock: true,
    },
    {
      id: 11,
      name: "Bộ lọc dầu Oil Filter – Toyota Hilux, Fortuner (15601-68010)",
      image: pro1,
      originalPrice: 320000,
      salePrice: 290000,
      discount: 9,
      status: "Giá cực sốc",
      category: "bo_loc_dau",
      brand: "Toyota",
      year: 2021,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 12,
      name: "Bộ lọc dầu Oil Filter – Mazda BT-50 (WL01-14-302)",
      image: pro2,
      originalPrice: 260000,
      salePrice: 230000,
      discount: 12,
      status: "Giá cực sốc",
      category: "bo_loc_dau",
      brand: "Mazda",
      year: 2019,
      origin: "Nhật Bản",
      inStock: true,
    },

    // Chua phân loại - Uncategorized
    {
      id: 13,
      name: "Cảm biến áp suất lốp TPMS – Universal (433MHz)",
      image: pro3,
      originalPrice: 850000,
      salePrice: 750000,
      discount: 12,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Universal",
      year: 2021,
      origin: "Trung Quốc",
      inStock: true,
    },
    {
      id: 14,
      name: "Đèn LED headlight H4 – Universal (6000K)",
      image: pro4,
      originalPrice: 1200000,
      salePrice: 1050000,
      discount: 13,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Universal",
      year: 2021,
      origin: "Hàn Quốc",
      inStock: true,
    },
    {
      id: 15,
      name: "Kính chiếu hậu điện tử – Universal (7 inch)",
      image: pro5,
      originalPrice: 2500000,
      salePrice: 2200000,
      discount: 12,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Universal",
      year: 2021,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 16,
      name: "Camera lùi không dây – Universal (HD 1080P)",
      image: pro1,
      originalPrice: 1800000,
      salePrice: 1600000,
      discount: 11,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Universal",
      year: 2021,
      origin: "Trung Quốc",
      inStock: true,
    },

    // Thêm 26 sản phẩm nữa để đủ 42 sản phẩm
    {
      id: 17,
      name: "Lọc gió động cơ Air Filter – Isuzu D-Max (8-98037-853-0)",
      image: pro2,
      originalPrice: 340000,
      salePrice: 300000,
      discount: 12,
      status: "Giá cực sốc",
      category: "loc_gio_dong_co",
      brand: "Isuzu",
      year: 2020,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 18,
      name: "Lọc gió động cơ Air Filter – Mitsubishi Triton (1500A023)",
      image: pro3,
      originalPrice: 360000,
      salePrice: 320000,
      discount: 11,
      status: "Giá cực sốc",
      category: "loc_gio_dong_co",
      brand: "Mitsubishi",
      year: 2020,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 19,
      name: "Lọc nhiên liệu Fuel Filter – Isuzu D-Max (8-98037-870-0)",
      image: pro4,
      originalPrice: 470000,
      salePrice: 420000,
      discount: 11,
      status: "Giá cực sốc",
      category: "loc_nhien_lieu",
      brand: "Isuzu",
      year: 2020,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 20,
      name: "Lọc nhiên liệu Fuel Filter – Mitsubishi Triton (MR552781)",
      image: pro5,
      originalPrice: 490000,
      salePrice: 440000,
      discount: 10,
      status: "Giá cực sốc",
      category: "loc_nhien_lieu",
      brand: "Mitsubishi",
      year: 2020,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 21,
      name: "Bộ lọc dầu Oil Filter – Isuzu D-Max (8-97358-950-0)",
      image: pro1,
      originalPrice: 290000,
      salePrice: 260000,
      discount: 10,
      status: "Giá cực sốc",
      category: "bo_loc_dau",
      brand: "Isuzu",
      year: 2020,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 22,
      name: "Bộ lọc dầu Oil Filter – Mitsubishi Triton (MD360935)",
      image: pro2,
      originalPrice: 310000,
      salePrice: 280000,
      discount: 10,
      status: "Giá cực sốc",
      category: "bo_loc_dau",
      brand: "Mitsubishi",
      year: 2020,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 23,
      name: "Lọc gió động cơ Air Filter – Nissan Navara (16546-EB70A)",
      image: pro3,
      originalPrice: 370000,
      salePrice: 330000,
      discount: 11,
      status: "Giá cực sốc",
      category: "loc_gio_dong_co",
      brand: "Nissan",
      year: 2019,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 24,
      name: "Lọc nhiên liệu Fuel Filter – Nissan Navara (16400-EB300)",
      image: pro4,
      originalPrice: 500000,
      salePrice: 450000,
      discount: 10,
      status: "Giá cực sốc",
      category: "loc_nhien_lieu",
      brand: "Nissan",
      year: 2019,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 25,
      name: "Bộ lọc dầu Oil Filter – Nissan Navara (15208-EB70A)",
      image: pro5,
      originalPrice: 330000,
      salePrice: 300000,
      discount: 9,
      status: "Giá cực sốc",
      category: "bo_loc_dau",
      brand: "Nissan",
      year: 2019,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 26,
      name: "Máy phát điện 12V – Universal (120A)",
      image: pro1,
      originalPrice: 3500000,
      salePrice: 3100000,
      discount: 11,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Bosch",
      year: 2021,
      origin: "Đức",
      inStock: true,
    },
    {
      id: 27,
      name: "Máy khởi động 12V – Universal (2.5kW)",
      image: pro2,
      originalPrice: 4200000,
      salePrice: 3800000,
      discount: 10,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Bosch",
      year: 2021,
      origin: "Đức",
      inStock: true,
    },
    {
      id: 28,
      name: "Bơm nước làm mát – Chevrolet Colorado (12681432)",
      image: pro3,
      originalPrice: 2800000,
      salePrice: 2500000,
      discount: 11,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Chevrolet",
      year: 2021,
      origin: "Đức",
      inStock: true,
    },
    {
      id: 29,
      name: "Bơm nước làm mát – Ford Ranger (1S7G-8501-DA)",
      image: pro4,
      originalPrice: 2900000,
      salePrice: 2600000,
      discount: 10,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Ford",
      year: 2020,
      origin: "Mỹ",
      inStock: true,
    },
    {
      id: 30,
      name: "Bơm nước làm mát – Toyota Hilux (16100-59275)",
      image: pro5,
      originalPrice: 3100000,
      salePrice: 2800000,
      discount: 10,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Toyota",
      year: 2021,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 31,
      name: "Lọc gió động cơ Air Filter – Honda Ridgeline (17220-5J6-A00)",
      image: pro1,
      originalPrice: 390000,
      salePrice: 350000,
      discount: 10,
      status: "Giá cực sốc",
      category: "loc_gio_dong_co",
      brand: "Honda",
      year: 2020,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 32,
      name: "Lọc nhiên liệu Fuel Filter – Honda Ridgeline (16901-5J6-A00)",
      image: pro2,
      originalPrice: 510000,
      salePrice: 460000,
      discount: 10,
      status: "Giá cực sốc",
      category: "loc_nhien_lieu",
      brand: "Honda",
      year: 2020,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 33,
      name: "Bộ lọc dầu Oil Filter – Honda Ridgeline (15400-PLM-A02)",
      image: pro3,
      originalPrice: 340000,
      salePrice: 310000,
      discount: 9,
      status: "Giá cực sốc",
      category: "bo_loc_dau",
      brand: "Honda",
      year: 2020,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 34,
      name: "Cảm biến oxy O2 – Universal (4 dây)",
      image: pro4,
      originalPrice: 1600000,
      salePrice: 1400000,
      discount: 13,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Bosch",
      year: 2021,
      origin: "Đức",
      inStock: true,
    },
    {
      id: 35,
      name: "Cảm biến MAP – Universal (3 bar)",
      image: pro5,
      originalPrice: 1200000,
      salePrice: 1050000,
      discount: 13,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Bosch",
      year: 2021,
      origin: "Đức",
      inStock: true,
    },
    {
      id: 36,
      name: "Cảm biến nhiệt độ nước – Universal",
      image: pro1,
      originalPrice: 800000,
      salePrice: 700000,
      discount: 13,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Bosch",
      year: 2021,
      origin: "Đức",
      inStock: true,
    },
    {
      id: 37,
      name: "Van EGR – Chevrolet Colorado (12619109)",
      image: pro2,
      originalPrice: 5500000,
      salePrice: 4900000,
      discount: 11,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Chevrolet",
      year: 2021,
      origin: "Đức",
      inStock: true,
    },
    {
      id: 38,
      name: "Van EGR – Ford Ranger (1679230)",
      image: pro3,
      originalPrice: 5800000,
      salePrice: 5200000,
      discount: 10,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Ford",
      year: 2020,
      origin: "Mỹ",
      inStock: true,
    },
    {
      id: 39,
      name: "Van EGR – Toyota Hilux (25620-30010)",
      image: pro4,
      originalPrice: 6200000,
      salePrice: 5600000,
      discount: 10,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Toyota",
      year: 2021,
      origin: "Nhật Bản",
      inStock: true,
    },
    {
      id: 40,
      name: "Turbo tăng áp – Universal (GT2052V)",
      image: pro5,
      originalPrice: 15000000,
      salePrice: 13500000,
      discount: 10,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Garrett",
      year: 2021,
      origin: "Mỹ",
      inStock: true,
    },
    {
      id: 41,
      name: "Intercooler – Universal (600x300x76mm)",
      image: pro1,
      originalPrice: 3800000,
      salePrice: 3400000,
      discount: 11,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Universal",
      year: 2021,
      origin: "Trung Quốc",
      inStock: true,
    },
    {
      id: 42,
      name: "Radiator tản nhiệt – Universal (Aluminum)",
      image: pro2,
      originalPrice: 4500000,
      salePrice: 4000000,
      discount: 11,
      status: "Giá cực sốc",
      category: "chua_phan_loai",
      brand: "Universal",
      year: 2021,
      origin: "Trung Quốc",
      inStock: true,
    },
  ],
};

export const filterOptions = {
  categories: [
    { id: "all", name: "Tất cả sản phẩm", count: 42 },
    { id: "loc_gio_dong_co", name: "Lọc gió động cơ - Air Filter", count: 8 },
    { id: "loc_nhien_lieu", name: "Lọc nhiên liệu - Fuel Filter", count: 8 },
    { id: "bo_loc_dau", name: "Bộ lọc dầu - Oil Filter", count: 8 },
    { id: "chua_phan_loai", name: "Chưa phân loại", count: 18 },
  ],
  priceRanges: [
    {
      id: "under_100k",
      name: "Dưới 100,000 đ",
      min: 0,
      max: 100000,
      tagColor: "purple",
    },
    {
      id: "100k_300k",
      name: "100,000 đ - 300,000 đ",
      min: 100000,
      max: 300000,
    },
    {
      id: "300k_500k",
      name: "300,000 đ - 500,000 đ",
      min: 300000,
      max: 500000,
    },
    {
      id: "over_500k",
      name: "Trên 500,000 đ",
      min: 500000,
      max: Infinity,
    },
  ],
  brands: [
    { id: "chevrolet", name: "Chevrolet", count: 8 },
    { id: "ford", name: "Ford", count: 6 },
    { id: "toyota", name: "Toyota", count: 6 },
    { id: "mazda", name: "Mazda", count: 4 },
    { id: "isuzu", name: "Isuzu", count: 3 },
    { id: "mitsubishi", name: "Mitsubishi", count: 3 },
    { id: "nissan", name: "Nissan", count: 3 },
    { id: "honda", name: "Honda", count: 3 },
    { id: "bosch", name: "Bosch", count: 5 },
    { id: "universal", name: "Universal", count: 8 },
    { id: "garrett", name: "Garrett", count: 1 },
  ],
  years: [
    { id: "2021", name: "2021", count: 24 },
    { id: "2020", name: "2020", count: 12 },
    { id: "2019", name: "2019", count: 6 },
  ],
  origins: [
    { id: "duc", name: "Đức", count: 8 },
    { id: "my", name: "Mỹ", count: 6 },
    { id: "nhat_ban", name: "Nhật Bản", count: 18 },
    { id: "han_quoc", name: "Hàn Quốc", count: 1 },
    { id: "trung_quoc", name: "Trung Quốc", count: 9 },
  ],
};
